export const categories = [
  {
    category: "Writing",
    unit: 1.21,
    subCategory: [
      "Essay",
      "Case study",
      "Report",
      "Research paper",
      "Presentation",
      "Annotated bibliography",
      "Article review",
      "Literature review",
      "Movie/Book review",
      "Reflective writing",
      "Other",
    ],
  },
  {
    category: "Class Work",
    unit: 1.29,
    subCategory: [
      "Mathematics",
      "Biology",
      "Physics",
      "Chemistry",
      "English",
      "Geography",
      "Religious Education",
      "Physical Education",
      "Statistics",
      "Other",
    ],
  },
  {
    category: "Programming",
    unit: 3.65,
    subCategory: [
      "Python",
      "Javascript",
      "Typescript",
      "C",
      "C++",
      "C#",
      "Java",
      "Swift",
      "Bash",
      "GO",
      "Matlab",
      "Rust",
      "Other",
    ],
  },
  {
    category: "Website Development",
    unit: 4.2,
    subCategory: [
      "Landing Page",
      "Business Website",
      "Portfolio",
      "Blog Website",
      "Event Website",
      "Personal Website",
      "E-Commerce",
      "Start-up Website",
      "Other",
    ],
  },
  {
    category: "Mobile Development",
    unit: 5.1,
    subCategory: ["Android", "IoS", "Other"],
  },
  {
    category: "Backend Development",
    unit: 6.3,
    subCategory: ["Python", "JS/NodeJS", "Java", "Go", "Other"],
  },
  {
    category: "UI/UX Design",
    unit: 3.58,
    subCategory: ["Figma", "Canva", "Other"],
  },
  {
    category: "Logo Design",
    unit: 3.01,
    subCategory: ["Personal Logo", "Business Logo", "Other"],
  },
  {
    category: "CAD Design",
    unit: 4.51,
    subCategory: ["Solid works", "Adobe", "CATIA", "AutoCAD", "Other"],
  },
  {
    category: "General Desing Work",
    unit: 2.57,
    subCategory: ["Any"],
  },
  {
    category: "Other",
    unit: 1.2,
    subCategory: ["Other"],
  },
];
